repos:
  - repo: builtin
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.16
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.8
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/astral-sh/ty-pre-commit
    rev: v0.0.82
    hooks:
      - id: ty
        args: [--isolated, --python=3.12, --extra=cf, --extra=dask]

  - repo: https://github.com/hukkin/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        args: [--number]
        additional_dependencies:
          - mdformat-beautysh
          - mdformat-config
          - mdformat-gfm
          - mdformat-gfm-alerts
          - mdformat-myst
          - mdformat-simple-breaks
          - mdformat-web

  - repo: local
    hooks:
      - id: spdx
        name: Add SPDX headers
        entry: uvx reuse==6.2.0 annotate
        language: system
        args:
          - --copyright=Albert M. W. Yau
          - --license=BSD-3-Clause
          - --merge-copyrights
          - --skip-unrecognised
        files: '^(pyproject\.toml|(?:src|tests)/.*\.(?:py|pyi))$'
