# SPDX-FileCopyrightText: 2026 Albert M. W. Yau
#
# SPDX-License-Identifier: BSD-3-Clause

"""Parity against fresh NCL 6.6.2/SPHEREPACK reference outputs."""

from __future__ import annotations

import os
from dataclasses import dataclass
from typing import Literal, cast

import numpy as np
import pytest
import xarray as xr

import spharmgrid as sg
from tests.ncl.reference import (
    DOMAINS,
    GRID_KINDS,
    INPUT_FAMILIES,
    SCHEMA_VERSION,
    data_array,
    expected_values,
    grid,
    load_reference,
)

pytestmark = [
    pytest.mark.parity,
    pytest.mark.ncl,
    pytest.mark.skipif(
        not os.environ.get("SPHARMGRID_NCL_REFERENCE_DIR"),
        reason=(
            "NCL reference outputs are generated by the dispatch-only NCL workflow"
        ),
    ),
]

_DOMAIN_ARGUMENTS = {
    "T42": "T42",
    "T5_42": "T5-42",
    "T42x10": "T42x10",
    "R21": "R21",
}
_REFERENCE_CASES = [
    pytest.param(grid_kind, input_family, id=f"{grid_kind}-{input_family}")
    for grid_kind in GRID_KINDS
    for input_family in INPUT_FAMILIES
]
_FILTER_CASES = [
    pytest.param(
        grid_kind,
        input_family,
        domain,
        taper,
        id=f"{grid_kind}-{input_family}-filter-{domain}-"
        f"{'taper' if taper is not None else 'hard'}",
    )
    for grid_kind, input_family in (
        (kind, family) for kind in GRID_KINDS for family in INPUT_FAMILIES
    )
    for domain in (*DOMAINS,)
    for taper in (None, 0.1)
]
_REGRID_CASES = [
    pytest.param(
        source_grid,
        input_family,
        target_grid,
        domain,
        taper,
        id=f"{source_grid}-{input_family}-to-{target_grid}-regrid-{domain}-"
        f"{'taper' if taper is not None else 'hard'}",
    )
    for source_grid, input_family in (
        (kind, family) for kind in GRID_KINDS for family in INPUT_FAMILIES
    )
    for target_grid in GRID_KINDS
    for domain in ("full", *DOMAINS)
    for taper in ((None,) if domain == "full" else (None, 0.1))
]


@dataclass(frozen=True, slots=True)
class _Tolerance:
    rtol: float
    atol: float


def _assert_close(
    actual: xr.DataArray | np.ndarray,
    expected: np.ndarray,
    tolerance: _Tolerance,
    label: str,
) -> None:
    actual_values = np.asarray(actual)
    difference = actual_values - expected
    scale = float(np.max(np.abs(expected)))
    relative_population = np.abs(expected) > max(scale * 1.0e-12, 1.0e-300)
    relative_error = (
        float(
            np.max(
                np.abs(difference[relative_population] / expected[relative_population])
            )
        )
        if np.any(relative_population)
        else 0.0
    )
    try:
        np.testing.assert_allclose(
            actual_values,
            expected,
            rtol=tolerance.rtol,
            atol=tolerance.atol,
        )
    except AssertionError as error:
        rms = float(np.sqrt(np.mean(difference**2)))
        raise AssertionError(
            f"{label}: max_abs={np.max(np.abs(difference)):.6e}, "
            f"rms={rms:.6e}, max_relative={relative_error:.6e}, "
            f"rtol={tolerance.rtol:.6e}, atol={tolerance.atol:.6e}"
        ) from error


def _common_tolerance(operation: str, grid_kind: str, input_family: str) -> _Tolerance:
    random_gaussian = grid_kind == "gl" and input_family == "random"
    if operation == "gradient":
        return _Tolerance(0.0, 3.0e-6 if random_gaussian else 2.0e-17)
    if operation == "kinematics":
        return _Tolerance(0.0, 4.0e-6 if random_gaussian else 2.0e-17)
    if operation == "inverse_gradient":
        return _Tolerance(0.0, 1.0e-13)
    if operation == "laplacian":
        return _Tolerance(
            0.0, 5.0e-11 if grid_kind == "cc" and input_family == "random" else 1.0e-20
        )
    if operation == "inverse_laplacian":
        if input_family == "random":
            if grid_kind == "cc":
                # Random CC fields stress the highest retained degrees.  The
                # measured absolute difference is 2.40e9 on fields of order
                # 1e12, caused by cancellation in two independent inverses.
                return _Tolerance(3.5e-3, 2.5e9)
            return _Tolerance(3.5e-3, 1.0e6)
        return _Tolerance(1.0e-14, 2.0e-2)
    if operation == "inverse_vector_laplacian":
        if input_family == "random":
            # The measured maxima are 3.34e9 (GL) and 2.37e9 (CC), against
            # fields of order 1e12; retain separate grid-specific bounds.
            return _Tolerance(3.5e-3, 3.5e9 if grid_kind == "gl" else 2.5e9)
        return _Tolerance(1.0e-14, 2.0e-2)
    if operation == "potential":
        if random_gaussian:
            # High-degree GL vector analysis differs most after inverse
            # Laplacian scaling; max measured error is 3.14e4.
            return _Tolerance(4.0e-2, 3.3e4)
        return _Tolerance(2.0e-12, 1.0e-6)
    if operation == "helmholtz":
        if random_gaussian:
            return _Tolerance(1.3e-1, 2.7e-1)
        return _Tolerance(0.0, 2.0e-12)
    if operation == "vector_laplacian":
        if input_family == "random":
            # The output itself is order 1e-10; the maximum measured
            # cross-implementation difference is 3.97e-11 on CC.
            return _Tolerance(2.5e-1, 4.2e-11)
        return _Tolerance(0.0, 1.0e-20)
    if operation == "wind":
        return _Tolerance(0.0, 2.0e-12)
    raise AssertionError(f"no NCL parity tolerance for {operation}")


def _spectral_tolerance(
    operation: Literal["filter", "regrid_scalar", "regrid_vector"],
    source_grid: str,
    input_family: str,
    target_grid: str | None,
    domain: str,
    taper: float | None,
) -> _Tolerance:
    if input_family == "analytic":
        return _Tolerance(0.0, 2.0e-11)
    if domain == "R21":
        # After applying the independent m<=21 boundary, the measured
        # maxima are 1.73e-5 (hard) and 1.42e-5 (taper) for scalar cases;
        # vector cases remain below 1.55e-5.
        return _Tolerance(0.0, 3.0e-5 if taper is None else 2.5e-5)
    if domain == "full":
        if operation == "filter":
            return _Tolerance(0.0, 2.0e-13)
        if operation == "regrid_scalar":
            same_grid = source_grid == target_grid
            return _Tolerance(0.0, 2.0e-13 if same_grid else 1.2e-5)
        return _Tolerance(0.0, 0.4)
    if taper is None:
        # Broadband random maxima are 3.46e-4 for scalar and 9.76e-4 for
        # vector regridding across the four grid-direction combinations.
        return _Tolerance(
            0.0,
            4.0e-4 if operation != "regrid_vector" else 1.1e-3,
        )
    # Tapered maxima are 1.20e-4 for scalar and 2.80e-4 for vector cases.
    return _Tolerance(
        0.0,
        1.5e-4 if operation != "regrid_vector" else 3.5e-4,
    )


def _fields(
    arrays: dict[str, np.ndarray],
    grid_kind: Literal["gl", "cc"],
    latitude_order: Literal["ascending", "descending"] = "ascending",
) -> tuple[xr.DataArray, xr.DataArray, xr.DataArray]:
    return cast(
        tuple[xr.DataArray, xr.DataArray, xr.DataArray],
        tuple(
            data_array(arrays, name, grid_kind, latitude_order=latitude_order)
            for name in ("scalar", "u", "v")
        ),
    )


@pytest.mark.parametrize(("grid_kind", "input_family"), _REFERENCE_CASES)
def test_ncl_reference_schema(
    grid_kind: Literal["gl", "cc"], input_family: Literal["analytic", "random"]
) -> None:
    arrays, metadata = load_reference(grid_kind, input_family)
    source = grid(grid_kind)
    assert metadata["schema_version"] == SCHEMA_VERSION
    assert metadata["ncl_version"] == "6.6.2"
    assert metadata["reference"] == "NCL 6.6.2 built-in SPHEREPACK"
    assert metadata["earth_radius_m"] == sg.EARTH_RADIUS_M
    assert metadata["latitude_order"] == "ascending"
    assert metadata["longitude_convention"] == "0_to_360_noncyclic"
    assert metadata["array_keys"] == sorted(arrays)
    np.testing.assert_array_equal(arrays["lat"], source.latitude)
    np.testing.assert_array_equal(arrays["lon"], source.longitude)
    assert arrays["scalar"].shape == (source.nlat, source.nlon)
    assert arrays["u"].shape == arrays["v"].shape == arrays["scalar"].shape
    assert arrays["lon"][0] == 0.0
    assert arrays["lon"][-1] < 360.0
    for target_kind in GRID_KINDS:
        target = grid(target_kind)
        np.testing.assert_array_equal(
            arrays[f"target_lat_{target_kind}"], target.latitude
        )
        np.testing.assert_array_equal(
            arrays[f"target_lon_{target_kind}"], target.longitude
        )


@pytest.mark.parametrize(("grid_kind", "input_family"), _REFERENCE_CASES)
def test_ncl_taper_weights(
    grid_kind: Literal["gl", "cc"], input_family: Literal["analytic", "random"]
) -> None:
    arrays, metadata = load_reference(grid_kind, input_family)
    degree = np.arange(43, dtype=np.float64)
    expected = np.ones(43, dtype=np.float64)
    expected[1:] = np.exp(
        np.log(float(metadata["taper"]))
        * (degree[1:] * (degree[1:] + 1.0) / (42.0 * 43.0)) ** 2
    )
    _assert_close(
        arrays["taper_weights"],
        expected,
        _Tolerance(0.0, 5.0e-16),
        f"{grid_kind}-{input_family}-taper-weights",
    )
    assert arrays["taper_weights"][-1] == pytest.approx(0.1, abs=5.0e-16)


@pytest.mark.parametrize(
    ("grid_kind", "input_family", "domain", "taper"), _FILTER_CASES
)
def test_ncl_scalar_filter(
    grid_kind: Literal["gl", "cc"],
    input_family: Literal["analytic", "random"],
    domain: str,
    taper: float | None,
) -> None:
    arrays, _ = load_reference(grid_kind, input_family)
    field = data_array(arrays, "scalar", grid_kind)
    actual = sg.filter(
        field,
        truncation=_DOMAIN_ARGUMENTS[domain],
        taper=taper,
        sht_threads=1,
    )
    key = f"filter_{domain}_{'taper' if taper is not None else 'hard'}"
    _assert_close(
        actual,
        expected_values(arrays, key, grid_kind),
        _spectral_tolerance("filter", grid_kind, input_family, None, domain, taper),
        f"{grid_kind}-{input_family}-{key}",
    )


@pytest.mark.parametrize(("grid_kind", "input_family"), _REFERENCE_CASES)
def test_ncl_untruncated_scalar_baseline(
    grid_kind: Literal["gl", "cc"], input_family: Literal["analytic", "random"]
) -> None:
    arrays, _ = load_reference(grid_kind, input_family)
    field = data_array(arrays, "scalar", grid_kind)
    actual = sg.filter(field, sht_threads=1)
    _assert_close(
        actual,
        arrays["filter_full_hard"],
        _spectral_tolerance("filter", grid_kind, input_family, None, "full", None),
        f"{grid_kind}-{input_family}-filter-full-hard",
    )


_SCALAR_OPERATIONS = ("gradient", "inverse_gradient", "laplacian", "inverse_laplacian")


@pytest.mark.parametrize(("grid_kind", "input_family"), _REFERENCE_CASES)
@pytest.mark.parametrize(
    "operation", _SCALAR_OPERATIONS, ids=lambda operation: f"scalar-{operation}"
)
def test_ncl_scalar_operators(
    grid_kind: Literal["gl", "cc"],
    input_family: Literal["analytic", "random"],
    operation: str,
) -> None:
    arrays, _ = load_reference(grid_kind, input_family)
    scalar = data_array(arrays, "scalar", grid_kind)
    if operation == "gradient":
        actual = sg.gradient(scalar, sht_threads=1)
        for name in ("gradient_eastward", "gradient_northward"):
            _assert_close(
                actual[name],
                arrays[name],
                _common_tolerance(operation, grid_kind, input_family),
                f"{grid_kind}-{input_family}-{operation}-{name}",
            )
        return
    if operation == "inverse_gradient":
        actual = sg.inverse_gradient(
            data_array(arrays, "gradient_eastward", grid_kind),
            data_array(arrays, "gradient_northward", grid_kind),
            sht_threads=1,
        )
    elif operation == "laplacian":
        actual = sg.laplacian(scalar, sht_threads=1)
    else:
        actual = sg.inverse_laplacian(scalar, sht_threads=1)
    _assert_close(
        actual,
        arrays[operation],
        _common_tolerance(operation, grid_kind, input_family),
        f"{grid_kind}-{input_family}-{operation}",
    )


_VECTOR_OPERATIONS = (
    "vorticity",
    "divergence",
    "kinematics",
    "streamfunction",
    "velocity_potential",
    "potentials",
    "rotational_wind",
    "divergent_wind",
    "wind_vorticity_divergence",
    "wind_potentials",
    "helmholtz",
    "vector_laplacian",
    "inverse_vector_laplacian",
)


@pytest.mark.parametrize(("grid_kind", "input_family"), _REFERENCE_CASES)
@pytest.mark.parametrize(
    "operation", _VECTOR_OPERATIONS, ids=lambda operation: f"vector-{operation}"
)
def test_ncl_vector_operators(
    grid_kind: Literal["gl", "cc"],
    input_family: Literal["analytic", "random"],
    operation: str,
) -> None:
    arrays, _ = load_reference(grid_kind, input_family)
    _, u, v = _fields(arrays, grid_kind)
    tolerance_operation = {
        "vorticity": "kinematics",
        "divergence": "kinematics",
        "kinematics": "kinematics",
        "streamfunction": "potential",
        "velocity_potential": "potential",
        "potentials": "potential",
        "rotational_wind": "wind",
        "divergent_wind": "wind",
        "wind_vorticity_divergence": "wind",
        "wind_potentials": "wind",
        "helmholtz": "helmholtz",
        "vector_laplacian": "vector_laplacian",
        "inverse_vector_laplacian": "inverse_vector_laplacian",
    }[operation]
    tolerance = _common_tolerance(tolerance_operation, grid_kind, input_family)
    if operation == "vorticity":
        actual = sg.vorticity(u, v, sht_threads=1)
        outputs = (("vorticity", actual),)
    elif operation == "divergence":
        actual = sg.divergence(u, v, sht_threads=1)
        outputs = (("divergence", actual),)
    elif operation == "kinematics":
        actual = sg.kinematics(u, v, sht_threads=1)
        outputs = (("vorticity", actual["vo"]), ("divergence", actual["d"]))
    elif operation == "streamfunction":
        outputs = (("streamfunction", sg.streamfunction(u, v, sht_threads=1)),)
    elif operation == "velocity_potential":
        outputs = (("velocity_potential", sg.velocity_potential(u, v, sht_threads=1)),)
    elif operation == "potentials":
        actual = sg.potentials(u, v, sht_threads=1)
        outputs = (
            ("streamfunction", actual["strf"]),
            ("velocity_potential", actual["vp"]),
        )
    elif operation == "rotational_wind":
        actual = sg.rotational_wind(
            data_array(arrays, "vorticity", grid_kind),
            source="vorticity",
            sht_threads=1,
        )
        outputs = (
            ("rotational_u", actual["u_rotational"]),
            ("rotational_v", actual["v_rotational"]),
        )
    elif operation == "divergent_wind":
        actual = sg.divergent_wind(
            data_array(arrays, "divergence", grid_kind),
            source="divergence",
            sht_threads=1,
        )
        outputs = (
            ("divergent_u", actual["u_divergent"]),
            ("divergent_v", actual["v_divergent"]),
        )
    elif operation == "wind_vorticity_divergence":
        actual = sg.wind(
            data_array(arrays, "vorticity", grid_kind),
            data_array(arrays, "divergence", grid_kind),
            source="vorticity_divergence",
            sht_threads=1,
        )
        outputs = (("wind_vo_d_u", actual["u"]), ("wind_vo_d_v", actual["v"]))
    elif operation == "wind_potentials":
        actual = sg.wind(
            data_array(arrays, "streamfunction", grid_kind),
            data_array(arrays, "velocity_potential", grid_kind),
            source="potentials",
            sht_threads=1,
        )
        outputs = (
            ("wind_potentials_u", actual["u"]),
            ("wind_potentials_v", actual["v"]),
        )
    elif operation == "helmholtz":
        actual = sg.helmholtz(u, v, sht_threads=1)
        outputs = (
            ("helmholtz_u_rotational", actual["u_rotational"]),
            ("helmholtz_v_rotational", actual["v_rotational"]),
            ("helmholtz_u_divergent", actual["u_divergent"]),
            ("helmholtz_v_divergent", actual["v_divergent"]),
        )
    elif operation == "vector_laplacian":
        actual = sg.vector_laplacian(u, v, sht_threads=1)
        outputs = (
            ("vector_laplacian_u", actual["u"]),
            ("vector_laplacian_v", actual["v"]),
        )
    else:
        actual = sg.inverse_vector_laplacian(u, v, sht_threads=1)
        outputs = (
            ("inverse_vector_laplacian_u", actual["u"]),
            ("inverse_vector_laplacian_v", actual["v"]),
        )
    for name, result in outputs:
        _assert_close(
            result,
            arrays[name],
            tolerance,
            f"{grid_kind}-{input_family}-{operation}-{name}",
        )


@pytest.mark.parametrize(
    ("source_grid", "input_family", "target_grid", "domain", "taper"),
    _REGRID_CASES,
)
def test_ncl_scalar_regrid(
    source_grid: Literal["gl", "cc"],
    input_family: Literal["analytic", "random"],
    target_grid: Literal["gl", "cc"],
    domain: str,
    taper: float | None,
) -> None:
    arrays, _ = load_reference(source_grid, input_family)
    field = data_array(arrays, "scalar", source_grid)
    actual = sg.regrid(
        field,
        grid(target_grid),
        truncation=None if domain == "full" else _DOMAIN_ARGUMENTS[domain],
        taper=taper,
        sht_threads=1,
    )
    suffix = "taper" if taper is not None else "hard"
    key = f"regrid_scalar_{target_grid}_{domain}_{suffix}"
    _assert_close(
        actual,
        expected_values(arrays, key, source_grid, target_grid=target_grid),
        _spectral_tolerance(
            "regrid_scalar", source_grid, input_family, target_grid, domain, taper
        ),
        f"{source_grid}-{input_family}-to-{target_grid}-{key}",
    )


@pytest.mark.parametrize(
    ("source_grid", "input_family", "target_grid", "domain", "taper"),
    _REGRID_CASES,
)
def test_ncl_vector_regrid(
    source_grid: Literal["gl", "cc"],
    input_family: Literal["analytic", "random"],
    target_grid: Literal["gl", "cc"],
    domain: str,
    taper: float | None,
) -> None:
    arrays, _ = load_reference(source_grid, input_family)
    _, u, v = _fields(arrays, source_grid)
    actual = sg.regrid_vector(
        u,
        v,
        grid(target_grid),
        truncation=None if domain == "full" else _DOMAIN_ARGUMENTS[domain],
        taper=taper,
        sht_threads=1,
    )
    suffix = "taper" if taper is not None else "hard"
    tolerance = _spectral_tolerance(
        "regrid_vector", source_grid, input_family, target_grid, domain, taper
    )
    for component in ("u", "v"):
        key = f"regrid_vector_{component}_{target_grid}_{domain}_{suffix}"
        _assert_close(
            actual[component],
            expected_values(arrays, key, source_grid, target_grid=target_grid),
            tolerance,
            f"{source_grid}-{input_family}-to-{target_grid}-{key}",
        )


@pytest.mark.parametrize(("grid_kind", "input_family"), _REFERENCE_CASES)
@pytest.mark.parametrize(
    "operation",
    ["filter", "gradient", "vorticity", "regrid", "regrid_vector"],
    ids=lambda operation: f"descending-{operation}",
)
def test_ncl_descending_latitude_normalization(
    grid_kind: Literal["gl", "cc"],
    input_family: Literal["analytic", "random"],
    operation: str,
) -> None:
    arrays, _ = load_reference(grid_kind, input_family)
    scalar, u, v = _fields(arrays, grid_kind, latitude_order="descending")
    if operation == "filter":
        actual = sg.filter(scalar, truncation="T42x10", taper=0.1, sht_threads=1)
        _assert_close(
            actual,
            expected_values(
                arrays, "filter_T42x10_taper", grid_kind, latitude_order="descending"
            ),
            _spectral_tolerance("filter", grid_kind, input_family, None, "T42x10", 0.1),
            f"{grid_kind}-{input_family}-descending-filter",
        )
    elif operation == "gradient":
        actual = sg.gradient(scalar, sht_threads=1)
        for name in ("gradient_eastward", "gradient_northward"):
            _assert_close(
                actual[name],
                expected_values(arrays, name, grid_kind, latitude_order="descending"),
                _common_tolerance("gradient", grid_kind, input_family),
                f"{grid_kind}-{input_family}-descending-{name}",
            )
    elif operation == "vorticity":
        actual = sg.vorticity(u, v, sht_threads=1)
        _assert_close(
            actual,
            expected_values(
                arrays, "vorticity", grid_kind, latitude_order="descending"
            ),
            _common_tolerance("kinematics", grid_kind, input_family),
            f"{grid_kind}-{input_family}-descending-vorticity",
        )
    elif operation == "regrid":
        target = "cc" if grid_kind == "gl" else "gl"
        actual = sg.regrid(scalar, grid(target), truncation="T42", sht_threads=1)
        _assert_close(
            actual,
            expected_values(
                arrays,
                f"regrid_scalar_{target}_T42_hard",
                grid_kind,
                target_grid=target,
            ),
            _spectral_tolerance(
                "regrid_scalar", grid_kind, input_family, target, "T42", None
            ),
            f"{grid_kind}-{input_family}-descending-regrid",
        )
    else:
        target = "cc" if grid_kind == "gl" else "gl"
        actual = sg.regrid_vector(u, v, grid(target, "descending"), sht_threads=1)
        tolerance = _spectral_tolerance(
            "regrid_vector", grid_kind, input_family, target, "full", None
        )
        for component in ("u", "v"):
            key = f"regrid_vector_{component}_{target}_full_hard"
            _assert_close(
                actual[component],
                expected_values(
                    arrays,
                    key,
                    grid_kind,
                    latitude_order="descending",
                    target_grid=target,
                ),
                tolerance,
                f"{grid_kind}-{input_family}-descending-{key}",
            )
